(prelude-require-packages '(ag
                            cyberpunk-theme
                            counsel
                            counsel-projectile
                            deft
                            dracula-theme
                            drag-stuff
                            dumb-jump
                            ;;evil
                            feature-mode
                            flycheck
                            git-gutter
                            git-timemachine
                            golden-ratio
                            ;helm-hunks
                            ivy
                            lua-mode
                            ;;magithub
                            multiple-cursors
                            nginx-mode
                            persp-projectile
                            rbenv
                            restclient
                            rich-minority
                            rspec-mode
                            rubocop
                            ruby-hash-syntax
                            ruby-tools
                            smart-mode-line
                            swiper
                            undo-tree
                            vimish-fold
                            ))
