(prelude-require-packages '(ag
                            cyberpunk-theme
                            deft
                            drag-stuff
                            evil
                            feature-mode
                            flycheck
                            git-gutter
                            git-timemachine
                            golden-ratio
                            persp-projectile
                            rbenv
                            restclient
                            rich-minority
                            rspec-mode
                            ruby-hash-syntax
                            ruby-tools
                            smart-mode-line
                            swiper
                            undo-tree
                            vimish-fold
                            ))
